apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: auth-service
spec:
replicas: 1
template:
metadata:
labels:
app: auth-service
spec:
containers:
  - name: auth-service
image: docker.io/yourdockerid/auth-service:0.001
ports:
  - containerPort: 80